language: go

go:
  - 1.14.x

os: linux

dist: bionic

env:
  - GO111MODULE=on

before_install:

install:
  - bash <(curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0)

before_script:
  - go generate
  - go vet ./...
  - golangci-lint run

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go build

before_deploy:

deploy:
  - provider: releases
    api_key: GITHUB_TOKEN
    on:
      tags: true

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

after_success:
  - bash <(curl -s https://codecov.io/bash)
