language: go

go:
  - 1.14.x

os: linux

dist: bionic

env:
  - GO111MODULE=on

before_install:
  - export TZ=Europe/Moscow

install:

before_script:

script:
  - go vet ./...
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go build

before_deploy:
  - mkdir release
  - bash <(VER=$(go generate); for ARCH in amd64 386 arm arm64; do GOARCH=$ARCH go build -ldflags "-X main.version=$VER"; tar -czf release/known-to-hugo-$VER-linux-$ARCH.tar.gz known-to-hugo LICENSE README.md CHANGELOG.md; done)
  - bash <(VER=$(go generate); for ARCH in amd64 386; do GOOS=windows GOARCH=$ARCH go build -ldflags "-X main.version=$VER"; zip -q release/known-to-hugo-$VER-windows-$ARCH.zip known-to-hugo.exe LICENSE README.md CHANGELOG.md; done)

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: release/*
    skip_cleanup: true
    on:
      tags: true

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  except:
    - /^dependabot\/.*$/
